import http from 'k6/http';
import { check, sleep } from 'k6';
import crypto from 'k6/crypto';
import encoding from 'k6/encoding';
import { createCoverage } from '/coverage.js';

// ---------------------------------------------------------------------------
// k6 load test of the BFF Elearning.
//
// Every operation of the contract (contracts/openapi.json, mounted as /openapi.json) has one
// handler below: the shared OpenAPI coverage module (mairie360/CICD tests/k6/coverage.js, see
// performance_test.sh) aborts at init when an operation has no handler, and fails the
// `operations_uncovered` threshold when a handler ends without sending its request. Adding a route
// to the BFF therefore means adding its handler here.
//
// Two scenarios share the handlers:
// - `crud` (2 VUs): `coverage.run()` calls every handler once per iteration, reads and writes, so
//   it carries the coverage gate. Handlers run path by path in contract order and, for one path,
//   in the order get, put, post, delete, options, head, patch, trace (so DELETE runs before PATCH).
//   Ratings, course administration and address edits have no upstream storage yet: they answer 501,
//   declared as the expected status of their request (`NOT_IMPLEMENTED`).
// - `reads`: replays only the GET handlers, as random learners of init-perf.sql.
// - `catalog_rush`: `GET /elearning/catalog` at a fixed arrival rate, failing on any dropped iteration.
// Every operation gets a p(95) threshold, whose budget depends on its family (`budgetOf`).
//
// MAIR-474: the stack also runs init-perf.sql (ELearning_API's seed: 300 formations of 10 modules,
// 2 000 learners enrolled in 15 formations each), every read checks that it got the learner's own
// profile and formations, and the thresholds are strict (every check passes, no failed request, no
// dropped iteration). K6_PROFILE sizes the load: `ci` (default) is what the 4 vCPU CI runner holds,
// `stress` is the high load, run by hand.
//
// The BFF resolves the session through BFF User /me: user 1 (Admin) and user 2 (User) are seeded
// by init-test.sql, both enrolled in the E-learning formation 4 (module 11, attachment 27), which
// the learner handlers read and complete through the E-learning API.
// ---------------------------------------------------------------------------

// The JWT_SECRET of the APIs, BFF User and this BFF in the test stack: random per run, generated by
// stack_secrets.sh (MAIR-474). No default: nothing is signed with a committed secret.
const JWT_SECRET = __ENV.JWT_SECRET;
if (!JWT_SECRET) throw new Error('JWT_SECRET is not set: run ./performance_test.sh, which generates it');
const USER_ID = __ENV.PERF_USER_ID || '2';
const ADMIN_ID = __ENV.PERF_ADMIN_ID || '1';
// E-learning formation seeded by init-test.sql.
const FIXTURE_COURSE_ID = '4';
const FIXTURE_CHAPTER_ID = '11';
const FIXTURE_CONTENT_ID = '27';
// Rows of init-perf.sql: learners 200001..202000; learner of rank i is enrolled in the 15 formations
// 5000 + (i + 20k) % 300, k = 0..14.
const LEARNERS = { first: 200001, count: 2000, formations: 15 };

const PROFILES = {
  ci: { readVus: 30, crudVus: 2, rushRate: 30 },
  stress: { readVus: 100, crudVus: 4, rushRate: 100 },
};
const PROFILE = PROFILES[__ENV.K6_PROFILE || 'ci'];
if (!PROFILE) throw new Error(`Unknown K6_PROFILE ${__ENV.K6_PROFILE}: ${Object.keys(PROFILES).join(', ')}`);

// Routes with no upstream storage yet answer 501: expected, so not counted in http_req_failed.
const NOT_IMPLEMENTED = { responseCallback: http.expectedStatuses(501) };

function b64url(value) {
  return encoding.b64encode(value, 'rawurl');
}

// Minimal HS256 JWT accepted by Core API / BFF User (sub + role + exp claims).
function mintJwt(sub, role) {
  const header = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const now = Math.floor(Date.now() / 1000);
  const payload = b64url(JSON.stringify({ sub, role, exp: now + 3600 }));
  const signingInput = `${header}.${payload}`;
  const signature = crypto.hmac('sha256', JWT_SECRET, signingInput, 'base64rawurl');
  return `${signingInput}.${signature}`;
}

function bearer(token) {
  return { Authorization: `Bearer ${token}` };
}

const learnerTokens = {};
/** A random seeded learner: its id, `Authorization` header and the ids of its formations. */
function randomLearner() {
  const rank = Math.floor(Math.random() * LEARNERS.count);
  const id = LEARNERS.first + rank;
  if (!learnerTokens[id]) learnerTokens[id] = bearer(mintJwt(String(id), 'user'));
  const formations = new Set();
  for (let k = 0; k < LEARNERS.formations; k += 1) formations.add(String(5000 + ((rank + 20 * k) % 300)));
  return { id, headers: learnerTokens[id], formations };
}

function json(response) {
  try {
    return response.json();
  } catch (_) {
    return null;
  }
}

/** The catalogue of `learner`: its own profile and a full first page of its own formations. */
function checkCatalog(response, learner, prefix) {
  return check(response, {
    [`${prefix} 200`]: (r) => r.status === 200,
    [`${prefix} lists the learner formations`]: (r) => {
      const body = json(r) || {};
      const courses = (body.catalog || {}).courses || [];
      return r.status === 200 && (body.user || {}).id === String(learner.id) && courses.length === 10
        && courses.every((course) => learner.formations.has(String(course.id)));
    },
  });
}

// The admin course routes take the whole course (id, title, description).
function courseBody(id, title) {
  return { id, title, description: 'Course created by the k6 load test', category: 'Integration', duration: '1 h' };
}

const handlers = {
  // --- Connectivity (public) ---
  'GET /health': ({ request }) =>
    check(request(), { 'health 200': (r) => r.status === 200 }),
  'GET /check_apis': ({ request }) =>
    check(request(), { 'check_apis 200': (r) => r.status === 200 }),

  // --- Admin: courses (501 until the E-learning API can edit formations) ---
  'POST /elearning/admin/courses': ({ request, data }) =>
    check(request({ body: courseBody('perf-course', 'k6 course'), headers: data.admin, params: NOT_IMPLEMENTED }), {
      'create course 501': (r) => r.status === 501,
    }),
  'DELETE /elearning/admin/courses/{courseId}': ({ request, data }) =>
    check(request({ path: { courseId: FIXTURE_COURSE_ID }, headers: data.admin, params: NOT_IMPLEMENTED }), {
      'delete course 501': (r) => r.status === 501,
    }),
  'PATCH /elearning/admin/courses/{courseId}': ({ request, data }) =>
    check(
      request({ path: { courseId: FIXTURE_COURSE_ID }, body: courseBody(FIXTURE_COURSE_ID, 'k6 course, patched'), headers: data.admin, params: NOT_IMPLEMENTED }),
      { 'patch course 501': (r) => r.status === 501 },
    ),

  // --- Learner ---
  'GET /elearning/catalog': ({ request }) => {
    const learner = randomLearner();
    checkCatalog(request({ query: { status: 'all', page: 1, pageSize: 10 }, headers: learner.headers }), learner, 'catalog');
  },
  'POST /elearning/courses/{courseId}/contents/{contentId}/complete': ({ request }) =>
    check(
      request({
        path: { courseId: FIXTURE_COURSE_ID, contentId: FIXTURE_CONTENT_ID },
        body: { chapterId: FIXTURE_CHAPTER_ID, completed: true },
      }),
      { 'complete content 200': (r) => r.status === 200 },
    ),
  'GET /elearning/profile': ({ request }) => {
    const learner = randomLearner();
    check(request({ headers: learner.headers }), {
      'profile 200': (r) => r.status === 200,
      'profile is the learner': (r) => r.status === 200 && ((json(r) || {}).user || {}).id === String(learner.id),
    });
  },
  'PATCH /elearning/profile': ({ request }) =>
    check(request({ body: { phone: '+33612345678' } }), {
      'patch profile 200': (r) => r.status === 200,
    }),
  'POST /elearning/courses/{courseId}/rating': ({ request }) =>
    check(request({ path: { courseId: FIXTURE_COURSE_ID }, body: { rating: 5 }, params: NOT_IMPLEMENTED }), {
      'rating 501': (r) => r.status === 501,
    }),
  'POST /elearning/courses/{courseId}/start': ({ request }) =>
    check(request({ path: { courseId: FIXTURE_COURSE_ID }, body: { source: 'catalog' } }), {
      'start 200': (r) => r.status === 200,
    }),
};

const coverage = createCoverage(handlers);
const readOperations = coverage.operations.filter((o) => o.method === 'GET');

// p(95) budget of an operation, per family.
function budgetOf({ op, method }) {
  if (op === 'GET /health') return 50; // process probe
  if (op === 'GET /check_apis') return 300; // -> Core + E-learning /health
  if (method === 'GET') return 600; // BFF User /me + E-learning API fan-out (formations, modules)
  return 800; // writes
}

const perOperationThresholds = {};
for (const operation of coverage.operations) {
  perOperationThresholds[`http_req_duration{op:${operation.op}}`] = [`p(95)<${budgetOf(operation)}`];
}

export const options = {
  scenarios: {
    reads: {
      executor: 'ramping-vus',
      exec: 'reads',
      stages: [
        { duration: '30s', target: Math.ceil(PROFILE.readVus / 2) }, // ramp-up
        { duration: '30s', target: PROFILE.readVus },
        { duration: '2m', target: PROFILE.readVus }, // steady load
        { duration: '20s', target: 0 }, // ramp-down
      ],
    },
    crud: {
      executor: 'constant-vus',
      exec: 'crud',
      vus: PROFILE.crudVus,
      duration: '3m20s',
    },
    catalog_rush: {
      executor: 'constant-arrival-rate',
      exec: 'catalogRush',
      startTime: '1m', // once the reads are at their peak
      rate: PROFILE.rushRate,
      timeUnit: '1s',
      duration: '1m',
      preAllocatedVUs: 30,
      maxVUs: 200,
    },
  },
  thresholds: {
    ...coverage.thresholds,
    ...perOperationThresholds,
    'http_req_duration{op:catalog_rush}': ['p(95)<600'],
    dropped_iterations: ['count==0'], // the rush kept its rate
    // Strict (MAIR-474): one wrong status, one wrong row or one failed request fails the run.
    http_req_failed: ['rate==0'],
    checks: ['rate==1'],
  },
};

export function setup() {
  return { admin: bearer(mintJwt(ADMIN_ID, 'admin')), user: bearer(mintJwt(USER_ID, 'user')) };
}

// Every GET handler, with a plain request() (no coverage accounting: `crud` owns the gate).
export function reads(data) {
  for (const operation of readOperations) {
    const request = (call = {}) =>
      http.get(coverage.url(operation.op, call.path, call.query), {
        headers: Object.assign({}, data.user, call.headers),
        tags: { op: operation.op },
      });
    handlers[operation.op]({ request, data, op: operation.op, method: operation.method, path: operation.path });
  }
  sleep(1);
}

export function catalogRush() {
  const learner = randomLearner();
  const op = 'GET /elearning/catalog';
  checkCatalog(
    http.get(coverage.url(op, {}, { status: 'all', page: 1, pageSize: 10 }), { headers: learner.headers, tags: { op: 'catalog_rush' } }),
    learner,
    'rush catalog',
  );
}

export function crud(data) {
  // User token by default; the /elearning/admin/* handlers pass the admin one.
  coverage.run({ headers: data.user, data });
  sleep(1);
}
